Repository mitodl/unified-ecommerce, pull requests merged in 2024-10, with the labels that each got.

#157 Fixes a few things in the events system
  README.md
  cart/views.py
  payments/api.py
  payments/api_test.py
  payments/hooks/post_sale.py
  payments/hooks/post_sale_test.py
  payments/models.py
  payments/serializers/v0/__init__.py
  payments/tasks.py
  payments/views/v0/__init__.py
  unified_ecommerce/settings.py
Labels: product:unified-ecommerce

#158 Redefine APISIX configuration in yaml
  .env.example
  README.md
  config/apisix/apisix.yaml
  config/apisix/apisix.yml
  config/apisix/config.yaml
  config/apisix/debug.yaml
  config/etcd/etcd.conf.yml
  docker-compose.yml
  scripts/bootstrap_apisix-home-keycloak.sh
  scripts/bootstrap_apisix.sh
Labels: Needs Review, product:unified-ecommerce

#159 Reworks OpenAPI generation/setup to mirror other projects
  config/apisix/apisix.yaml
  frontends/api/src/generated/.openapi-generator/VERSION
  frontends/api/src/generated/v0/.gitignore
  frontends/api/src/generated/v0/.npmignore
  frontends/api/src/generated/v0/.openapi-generator-ignore
  frontends/api/src/generated/v0/.openapi-generator/FILES
  frontends/api/src/generated/v0/.openapi-generator/VERSION
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v0/base.ts
  frontends/api/src/generated/v0/common.ts
  frontends/api/src/generated/v0/configuration.ts
  frontends/api/src/generated/v0/git_push.sh
  frontends/api/src/generated/v0/index.ts
  openapi/__init__.py
  openapi/apps.py
  openapi/exceptions.py
  openapi/hooks.py
  openapi/management/__init__.py
  openapi/management/commands/__init__.py
  openapi/management/commands/generate_openapi_spec.py
  openapi/settings_spectacular.py
  openapi/specs/v0.yaml
  openapi/urls.py
  payments/models.py
  payments/serializers/v0/__init__.py
  payments/urls.py
  payments/views/v0/__init__.py
  payments/views/v0/urls.py
  scripts/generate_openapi.sh
  scripts/openapi-configs/templates/modelEnum.mustache
  scripts/openapi-configs/typescript-axios-v0.yaml
  scripts/test/openapi_spec_check.sh
  system_meta/urls.py
  unified_ecommerce/permissions.py
  unified_ecommerce/settings.py
  unified_ecommerce/urls.py
  unified_ecommerce/urls_spectacular.py
  unified_ecommerce/viewsets.py
Labels: product:unified-ecommerce

#160 5654 update apis for shopping cartbasket
  cart/urls.py
  cart/views.py
  config/apisix/apisix.yaml
  payments/api.py
  payments/api_test.py
  payments/views/v0/__init__.py
  payments/views/v0/urls.py
  system_meta/migrations/0005_integratedsystem_payment_process_redirect_url.py
  system_meta/models.py
Labels: Needs Review

#162 Fixing some API generation stuff, bit of cleanup
  frontends/api/src/generated/v0/.openapi-generator-ignore
  frontends/api/src/generated/v0/api.ts
  frontends/api/src/generated/v0/base.ts
  frontends/api/src/generated/v0/common.ts
  frontends/api/src/generated/v0/configuration.ts
  frontends/api/src/generated/v0/index.ts
  openapi.yaml
  openapi/specs/v0.yaml
  payments/serializers/v0/__init__.py
  payments/views/v0/__init__.py
  scripts/openapi-configs/typescript-axios-v0.yaml
Labels: product:unified-ecommerce

#161 Separate baskets/checkout for each integrated system and user
  cart/templates/cart.html
  cart/urls.py
  cart/views.py
  payments/api.py
  payments/api_test.py
  payments/factories.py
  payments/migrations/0004_remove_existing_baskets.py
  payments/migrations/0005_basket_integrated_system_alter_basket_user.py
  payments/models.py
  payments/views/v0/__init__.py
  payments/views/v0/urls.py
Labels: Needs Review
