Repository mitodl/unified-ecommerce, pull requests merged in 2024-09, with the labels that each got.

#132 Adds Keycloak to the APISIX buildout
  .gitignore
  .secrets.baseline
  README-keycloak.md
  README.md
  config/keycloak/realms/default-realm.json
  config/keycloak/tls/README.md
  config/keycloak/tls/tls.crt.default
  config/keycloak/tls/tls.key.default
  docker-compose-apisix.yml
Labels: Needs Review, product:unified-ecommerce

#136 Update the session invalidation code
  authentication/api.py
  unified_ecommerce/middleware.py
Labels: product:unified-ecommerce

#152 5557 ecommerce determine how to handle order state
  payments/migrations/0001_add_order_and_basket_models.py
  payments/migrations/0003_alter_order_state.py
  payments/models.py
  poetry.lock
  pyproject.toml
Labels: Needs Review

#153 Add migrations to release script
  scripts/heroku-release-phase.sh
Labels: Needs Review

#135 Add events system
  cart/templates/cart.html
  cart/views.py
  payments/admin.py
  payments/api.py
  payments/constants.py
  payments/hooks/__init__.py
  payments/hooks/post_sale.py
  payments/hooks/post_sale_test.py
  payments/hookspecs.py
  payments/models.py
  payments/models_test.py
  payments/serializers/v0/__init__.py
  poetry.lock
  pyproject.toml
  scripts/bootstrap_apisix-home-keycloak.sh
  system_meta/admin.py
  system_meta/factories.py
  system_meta/migrations/0003_add_system_webhook_url_fields.py
  system_meta/migrations/0004_rename_sale_succeeded_webhook_url_integratedsystem_webhook_url_and_more.py
  system_meta/models.py
  system_meta/views.py
  unified_ecommerce/constants.py
  unified_ecommerce/plugin_manager.py
  unified_ecommerce/serializers.py
Labels: Needs Review, product:unified-ecommerce

#154 REmove lingering django-fsm
  payments/admin.py
  payments/migrations/0001_add_order_and_basket_models.py
  poetry.lock
  pyproject.toml
  unified_ecommerce/settings.py
Labels: Needs Review
